// <auto-generated />
using System;
using GamePortalMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamePortalMVC.Migrations
{
    [DbContext(typeof(DbAuthContext))]
    partial class DbAuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GamePortalMVC.Data.Repositories.Account", b =>
                {
                    b.Property<int>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Admin")
                        .HasColumnType("int");

                    b.Property<string>("IP_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("block")
                        .HasColumnType("int");

                    b.Property<DateTime>("datePassword")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("last_login_server_idx")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("point")
                        .HasColumnType("int");

                    b.HasKey("account_id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("GamePortalMVC.Data.Repositories.Block", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<int?>("account_id1")
                        .HasColumnType("int");

                    b.Property<string>("ban_disc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ban_owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("typeBlock")
                        .HasColumnType("int");

                    b.Property<DateTime>("unban_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("account_id1");

                    b.ToTable("Block");
                });

            modelBuilder.Entity("GamePortalMVC.Data.Repositories.Block", b =>
                {
                    b.HasOne("GamePortalMVC.Data.Repositories.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id1");
                });
#pragma warning restore 612, 618
        }
    }
}
